//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fb2ePubGui.UpdateSettingsControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutoUpdateFreqCheckTimeSliceTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoUpdateFreqCheckTimeSliceTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fb2ePubGui.UpdateSettingsControl.AutoUpdateFreqCheckTimeSliceTranslations", typeof(AutoUpdateFreqCheckTimeSliceTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every start.
        /// </summary>
        internal static string AutoUpdateFreqCheckTimeSlice_EveryRun_Text {
            get {
                return ResourceManager.GetString("AutoUpdateFreqCheckTimeSlice_EveryRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once a day.
        /// </summary>
        internal static string AutoUpdateFreqCheckTimeSlice_OnceADay_Text {
            get {
                return ResourceManager.GetString("AutoUpdateFreqCheckTimeSlice_OnceADay_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once a months.
        /// </summary>
        internal static string AutoUpdateFreqCheckTimeSlice_OnceAMonth_Text {
            get {
                return ResourceManager.GetString("AutoUpdateFreqCheckTimeSlice_OnceAMonth_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once a week.
        /// </summary>
        internal static string AutoUpdateFreqCheckTimeSlice_OnceAWeek_Text {
            get {
                return ResourceManager.GetString("AutoUpdateFreqCheckTimeSlice_OnceAWeek_Text", resourceCulture);
            }
        }
    }
}
