//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fb2ePubGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fb2ePubGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default settings file not found.
        /// </summary>
        internal static string AboutBox_AboutBox_Default_settings_file_not_found {
            get {
                return ResourceManager.GetString("AboutBox_AboutBox_Default_settings_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting file: {0}..
        /// </summary>
        internal static string Converting_File {
            get {
                return ResourceManager.GetString("Converting_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default settings file: {0},  ({1}).
        /// </summary>
        internal static string Default_Settings_File {
            get {
                return ResourceManager.GetString("Default_Settings_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap epub_logo_color_book {
            get {
                object obj = ResourceManager.GetObject("epub-logo-color-book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0} processed..
        /// </summary>
        internal static string File_Processed {
            get {
                return ResourceManager.GetString("File_Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0} skipped due error..
        /// </summary>
        internal static string File_Skipped_toError {
            get {
                return ResourceManager.GetString("File_Skipped_toError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished to convert {0} files..
        /// </summary>
        internal static string Finished_To_Convert_Files {
            get {
                return ResourceManager.GetString("Finished_To_Convert_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborting conversion.
        /// </summary>
        internal static string FormGUI_AbortConversion_Aborting_conversion {
            get {
                return ResourceManager.GetString("FormGUI_AbortConversion_Aborting_conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to abort conversion?.
        /// </summary>
        internal static string FormGUI_AbortConversion_Are_you_sure_you_wish_to_abort_conversion_ {
            get {
                return ResourceManager.GetString("FormGUI_AbortConversion_Are_you_sure_you_wish_to_abort_conversion_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select FB2 files to convert.
        /// </summary>
        internal static string FormGUI_buttonConvert_Click_Please_select_FB2_files_to_convert {
            get {
                return ResourceManager.GetString("FormGUI_buttonConvert_Click_Please_select_FB2_files_to_convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading version file.
        /// </summary>
        internal static string FormGUI_checkForUpdateToolStripMenuItem_Click_Error_downloading_version_file {
            get {
                return ResourceManager.GetString("FormGUI_checkForUpdateToolStripMenuItem_Click_Error_downloading_version_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version is most current.
        /// </summary>
        internal static string FormGUI_checkForUpdateToolStripMenuItem_Click_The_version_is_most_current {
            get {
                return ResourceManager.GetString("FormGUI_checkForUpdateToolStripMenuItem_Click_The_version_is_most_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version check.
        /// </summary>
        internal static string FormGUI_checkForUpdateToolStripMenuItem_Click_Version_check {
            get {
                return ResourceManager.GetString("FormGUI_checkForUpdateToolStripMenuItem_Click_Version_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG folder: {0}.
        /// </summary>
        internal static string Log_Folder {
            get {
                return ResourceManager.GetString("Log_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving file: {0}..
        /// </summary>
        internal static string Saving_File {
            get {
                return ResourceManager.GetString("Saving_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started to convert {0} files..
        /// </summary>
        internal static string Started_To_ConvertFiles {
            get {
                return ResourceManager.GetString("Started_To_ConvertFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting....
        /// </summary>
        internal static string Status_Converting {
            get {
                return ResourceManager.GetString("Status_Converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading downloaded version file.
        /// </summary>
        internal static string UpdateChecker_CheckForUpdate_Error_loading_downloaded_version_file {
            get {
                return ResourceManager.GetString("UpdateChecker_CheckForUpdate_Error_loading_downloaded_version_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.fb2epub.net/eng/index.html#latest.
        /// </summary>
        internal static string UpdateURL {
            get {
                return ResourceManager.GetString("UpdateURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Resources from: {0}.
        /// </summary>
        internal static string Using_Resources_From {
            get {
                return ResourceManager.GetString("Using_Resources_From", resourceCulture);
            }
        }
    }
}
