//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterFB2EPub {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ManualResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManualResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegisterFB2EPub.ManualResource", typeof(ManualResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FB2EPUB Shell extension |{0}.
        /// </summary>
        internal static string browseRequest {
            get {
                return ResourceManager.GetString("browseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select location of {0} to register.
        /// </summary>
        internal static string browseTitle {
            get {
                return ResourceManager.GetString("browseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exitButton {
            get {
                return ResourceManager.GetString("exitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to exit?.
        /// </summary>
        internal static string exitMessage {
            get {
                return ResourceManager.GetString("exitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit registration wizard.
        /// </summary>
        internal static string exitTitle {
            get {
                return ResourceManager.GetString("exitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string finishButton {
            get {
                return ResourceManager.GetString("finishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;&gt;.
        /// </summary>
        internal static string nextButton {
            get {
                return ResourceManager.GetString("nextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string noAnswer {
            get {
                return ResourceManager.GetString("noAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Back.
        /// </summary>
        internal static string prevButton {
            get {
                return ResourceManager.GetString("prevButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to avoid registeration for {0} extension.
        /// </summary>
        internal static string radioButtonNotRegisterTip {
            get {
                return ResourceManager.GetString("radioButtonNotRegisterTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to register for {0} extension.
        /// </summary>
        internal static string radioButtonRegisterAnyTip {
            get {
                return ResourceManager.GetString("radioButtonRegisterAnyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register {0} extension :.
        /// </summary>
        internal static string registerExtension {
            get {
                return ResourceManager.GetString("registerExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yesAnswer {
            get {
                return ResourceManager.GetString("yesAnswer", resourceCulture);
            }
        }
    }
}
