//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fb2epubSettings.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Fb2epubSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fb2epubSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fb2epubSettings.Resources.Fb2epubSettings", typeof(Fb2epubSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a destination folder.
        /// </summary>
        internal static string AddPathForm_buttonSelect_Click_Please_select_a_destination_folder {
            get {
                return ResourceManager.GetString("AddPathForm_buttonSelect_Click_Please_select_a_destination_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Adobe XPGT template file.
        /// </summary>
        internal static string ConverterSettingsForm_buttonBrowseForXPGT_Click_Please_select_Adobe_XPGT_template_file {
            get {
                return ResourceManager.GetString("ConverterSettingsForm_buttonBrowseForXPGT_Click_Please_select_Adobe_XPGT_template" +
                        "_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font used.
        /// </summary>
        internal static string ConverterSettingsForm_buttonRemoveFont_Click_Font_used {
            get {
                return ResourceManager.GetString("ConverterSettingsForm_buttonRemoveFont_Click_Font_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font {0}  is used by CSS elements. Please unassign them first before deleting.
        /// </summary>
        internal static string ConverterSettingsForm_buttonRemoveFont_FontNameMessage {
            get {
                return ResourceManager.GetString("ConverterSettingsForm_buttonRemoveFont_FontNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t enable Single Destination mode - no path defined as shell path.
        /// </summary>
        internal static string ConverterSettingsForm_radioButtonSDEnabled_CheckedChanged_Can_t_enable_Single_Destination_mode___no_path_defined_as_shell_path {
            get {
                return ResourceManager.GetString("ConverterSettingsForm_radioButtonSDEnabled_CheckedChanged_Can_t_enable_Single_Des" +
                        "tination_mode___no_path_defined_as_shell_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting error.
        /// </summary>
        internal static string ConverterSettingsForm_radioButtonSDEnabled_CheckedChanged_Setting_error {
            get {
                return ResourceManager.GetString("ConverterSettingsForm_radioButtonSDEnabled_CheckedChanged_Setting_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font family name can&apos;t be empty.
        /// </summary>
        internal static string EditFontFamilyForm_textBoxFontFamilyName_Validating_Font_family_name_can_t_be_empty {
            get {
                return ResourceManager.GetString("EditFontFamilyForm_textBoxFontFamilyName_Validating_Font_family_name_can_t_be_emp" +
                        "ty", resourceCulture);
            }
        }
    }
}
